<?php
/**
 * Faker nicknames provider
 *
 * @author [SC]Smash3r <scsmash3r@gmail.com>
 *
 * @version 1.0
 *
 * @link https://github.com/Outstyle/website
 * @license Beerware
 */
namespace console\components\Faker;

class Nickname extends \Faker\Provider\Person
{
    protected static $maleNicknames = array(
      '3D Waffle','Hightower','Papa Smurf',
      '57 Pixels','Hog Butcher','Pepper Legs',
      '101','Houston','Pinball Wizard',
      'Accidental Genius','Hyper','Pluto',
      'Alpha','Jester','Pogue',
      'Airport Hobo','Jigsaw','Prometheus',
      'Bearded Angler','Jokerz Grin','Psycho Thinker',
      'Beetle King','Judge','Pusher',
      'Bitmap','Junkyard Dog','Riff Raff',
      'Blister','K-9','Roadblock',
      'Bowie','Keystone','Rooster',
      'Bowler','Kickstart','Sandbox',
      'Breadmaker','Kill Switch','Scrapper',
      'Broomspun','Kingfisher','Screwtape',
      'Buckshot','Kitchen','Sexual Chocolate',
      'Bugger','Knuckles','Shadow Chaser',
      'Cabbie','Lady Killer','Sherwood Gladiator',
      'Candy Butcher','Liquid Science','Shooter',
      'Capital F','Little Cobra','Sidewalk Enforcer',
      'Captain Peroxide','Little General','Skull Crusher',
      'Celtic Charger','Lord Nikon','Sky Bully',
      'Cereal Killer','Lord Pistachio','Slow Trot',
      'Chicago Blackout','Mad Irishman','Snake Eyes',
      'Chocolate Thunder','Mad Jack','Snow Hound',
      'Chuckles','Mad Rascal','Sofa King',
      'Commando','Manimal','Speedwell',
      'Cool Whip','Marbles','Spider Fuji',
      'Cosmo','Married Man','Springheel Jack',
      'Crash Override','Marshmallow','Squatch',
      'Crash Test','Mental','Stacker of Wheat',
      'Crazy Eights','Mercury Reborn','Sugar Man',
      'Criss Cross','Midas','Suicide Jockey',
      'Cross Thread','Midnight Rambler','Swampmasher',
      'Cujo','Midnight Rider','Swerve',
      'Dancing Madman','Mindless Bobcat','Tacklebox',
      'Dangle','Mr. 44','Take Away',
      'Dark Horse','Mr. Fabulous','Tan Stallion',
      'Day Hawk','Mr. Gadget','The China Wall',
      'Desert Haze','Mr. Lucky','The Dude',
      'Digger','Mr. Peppermint','The Flying Mouse',
      'Beat Thunder','Mr. Spy','The Happy Jock',
      'Floor Potato','Mr. Thanksgiving','The Howling Swede',
      'Dr. Cocktail','Mr. Wholesome','Thrasher',
      'Dredd','Mud Pie Man','Toe',
      'Dropkick','Mule Skinner','Toolmaker',
      'Drop Stone','Murmur','Tough Nut',
      'Drugstore Cowboy','Nacho','Trip',
      'Easy Sweep','Natural Mess','Troubadour',
      'Electric Player','Necromancer','Turnip King',
      'Esquire','Neophyte Believer','Twitch',
      'Fast Draw','Nessie','Vagabond Warrior',
      'Flakes','New Cycle','Voluntary',
      'Flint','Nickname Master','Vortex',
      'Freak','Nightmare King','Washer',
      'Gas Man','Night Train','Waylay Dave',
      'Glyph','Old Man Winter','Wheels',
      'Grave Digger','Old Orange Eyes','Wooden Man',
      'Guillotine','Old Regret','Woo Woo',
      'Gunhawk','Onion King','Yellow Menace',
      'HKW','Osprey','Zero Charisma',
      'Highlander Monk','Overrun','Zesty Dragon',
      'Mammoth 2','Blinker','FearLeSS',
      'Slug-em-dog','RawSkills','Danqqqqq',
      '3P-own','VileHero','Predator',
      'Freaky Ratbuster','NeoGermal','FireBrang',
      'Fatsy Bear','HolyCombo','ThickSKN',
      'Dark Matter','BuffFreak','HOV',
      '2nd Hand Joe','ThermalMode','Flotsams54',
      'Redneck Giorgio','CodeExia','Roadspike',
      'Mechani-Man','Kazami of Truth','Gbbledgoodk',
      'High Beam','Eye Devil','Swing Setter',
      'Tea Kettle','MrOnsTr','Wrangler Jim',
      'Flint Cast-Iron','Kinged','Lucifurious',
      'Lewd Dice','RZR','LerveDr',
      'Flyswat Briggs','Legacy','Shade Nightman',
      'PP Dubs','Prone','Hemingway Mirmillone',
      'Scooby Did','Stealth','Slinger',
      'Preach Man','Unseen','Crossing Guard',
      'Bad Bond','Force','FRMhndshk',
      'Easy Mac','Sky','SkyGod',
      'Toxic-oxide','Silent','GiddeeUP',
      'Irish Dze','Apex','DragonBlood',
      'Tse Tse Guy','Shay','IceDog',
      'Dallas Foxface','Sloth','Lounge Master',
      'Sprinkle Lovenuts','Sokol','DeathDancer',
      'Zorkle Sporkle','Skool','Pompeii Unicorn',
      'Noise Toy','Flash','Achilles Mountain',
      'Whip Chu','Elektrik','Bad Badminton',
      'Sly Silvermoon','LocKz','THRESHmSTR',
      'Tin Mutt','ReiGnZ','High-Fructose',
      'Sweet Bacon','Coldy','Sepukku',
      'Crazy Rox','Beo','Valley Guardian',
      '1st Degree','Ice','Sw00sh',
      'Bom Crossed','Unleashed','Ba1t',
      'Sick Saurus','Corny','SneakerKid',
      'Mad Viral','Steel','ShadowFax',
      'Clang Glyph','Ex0tic','Hermopolis',
      'xFRST','VPR','ManManMan',
      'Mosquit-No','LyRz','Firedog',
      'ELLerG!c','Lime','German Coach',
      'Hex Panther','Energy','Y0dler',
      'xSTORMx','Blade','WeldMaster',
      'Die Slice','Tunez','Steel Cut Toe',
      'Free Ham','Truth','Forger',
      'Dr. Jam Man','Lskeee','Black Walnut',
      'Seattle Jay','Pexxious','Journeyman',
      'RDTN','Venious','Plegasus',
      'Whip 2T','Grotas','Carrot Joker',
      'Skirble','Sherm','Switch',
      'Solitaire','Gro','Hobo Samurai',
      'Prof. Smirk','Indestructible Potato','Good William',
      'GuTzd','Kamikaze Grandma','Infinite Hole',
      'Are Ess Tee','Badger the Burglar','Sw33per',
      'Sir Squire','Mauve Cactus','Hidden Tree',
      'Deano','Bruh','AxelRoad',
      'Uncle Buddy','Fadey','Goldman',
      'Copilot','Z-Boy','Fl00d',
      'Bones','DZE','Danger Menace',
      'Vermilion','Muzish','Hang 11',
      'TrinitySoul','Cooger','Delicious Wing',
      'BlackExcalibur','Kazmii','Doz',
      'Risen','AirportHobo XD','Prez Dog',
      'ShadowDancer','Cumulo','Baked ZD',
      'Con Mammoth','D-Hog-Day','Pinball Esq',
      'CommandX','Houston Rocket','Third Moon',
      'Stallion Patton','Hyper Kong','Elder Pogue',
      'Rando Tank','JesterZilla','Lord Theus',
      'Omega Sub','JigKraken','Uncle Psycho',
      'Station WMD','FrankenGrin','Sir Shove',
      'Goatee Shield','The Final Judgement','Trash Master',
      'Bug Blitz','Landfill Max','Knight Light',
      'Bit Sentinel','K-Tin Man','Father Abbot',
      'Blistered Outlaw','Scare Stone','Admiral Tot',
      'RedFeet','Chew Chew','Scrapple',
      'Renegade Slugger','Solo Kill','Prof. Screw',
      'ManMaker','RedFisher','Trick Baron',
      'General Broomdog','Automatic Slicer','Shadow Bishop',
      'Raid Bucker','Fist Wizard','Centurion Sherman',
      'Atomic Blastoid','Doz Killer','Don Stab',
      'Bootleg Taximan','Liquid Death','Earl of Arms',
      'FlyGuardX','Baby Brown','Gov Skull',
      'Guncap Slingbad','General Finish','Sky Herald',
      'Pistol Hydro','Mt. Indiana','Lope Lope',
      'Greek Rifle','Rocky Highway','Seal Snake',
      'Poptart AK47','Mad Robin','Snow Pharaoh',
      'The Shield Toronto','Jack Cassidy','Saint La-Z-Boy',
      'Twix Bond','Mad Kid','Sultan of Speed',
      'Bazooka Har-de-har','DanimalDaze','Wolf Tribune',
      'Demand Chopper','Super Flick','B@d B0y',
      'Cool Law Topping','Taz Ringer','Frosty Squid',
      'Universe Bullet','Mallow Man','Coma Stalk',
      'Crash Enforcer','Mental Prophet','Scratch Man',
      'Howitzer Rise','Iron Jesus','Suicide Crusher',
      'Eight Patrol','GoldTouch','Troublemasher',
      'CosPlatoon','Midnight Bat','Viceswerve',
      'Saber-RED','Lincoln Rider','BoomerBox',
      'AlertXis','Canine Hannibal','Grabber',
      'Dance Cannon','Darth 44','Stud Buster',
      'Amphibi-Dangerous','Mr. Alien','Brick Mooch',
      'DARK HQ','Sir Shark','Hella Fella',
      'Armed Hawk','Lucky Martian','BuzzMouse',
      'Napoleonic Haze','Tabasco Dracula','BuzzBait',
      'Patton Digger','Red Hot Kevorkian','The Belgian',
      'Thunder Tank','CZR','DreadSherX',
      'Potato Sub','JK Friend','SubWoof330',
      'Dr. WMD','Mud Finger','Tornado Maker',
      'Marine Dre','Mule Lock','Thunder Nut',
      'Round Kick Boomer','Shwatson','Lightening Trip',
      'Stone Boomstick','Grinch Cheese','Storm Master',
      'Cowboy Booter','Popeye Wipeout','King Bass',
      'Insane SweepKick','NecroBull','Gr8 Flick',
      'Duke Electro','Daffy Neo','West Warrior',
      'Doughboy, Esq','Nessie Pork','East Army',
      'Fast FLAK','New Magoo','Rusty Vortex',
      'Slint FUBAR','Master Jetson','Sun Washer',
      'Hoover Spark','King Panther','Sly Bible',
      'Pyscho Hun','Gumby Train','Atlantic Rim',
      'Sapiens','Winter Underdog','Wooden German',
      'Genghis Glyph','Sylvester Eye','High Woo',
      'Grave Scuttlebutt','Old Felix','Low Menace',
      'Guillotine Trigger','Jungle King','Zero Corn',
      'Trigger Warming','Count Eagle','Mustard Centaur',
      'High Deck','Cardinal Rebel','Twiddle Twix',
      'Upper D3ckR','Senior Smurf','Spicy Thunder',
      'HighBomber','Red Pepper','Foot-long Fry',
      'Boomerang','Sticks','Horsehide',
      'Helmet','Tackle','Hose',
      'The Bat','Wishbone','Hot Box',
      'Field Goal','X','Rain Delay',
      'Touchdown','Z','Interstate',
      'TD','ZD','J-Run',
      'Foul Play','ZB','Junk',
      'Red Flag','Ace','Knuckleball',
      'Endzone','Airmail','Knee-Buckler',
      'Defense','Aspirin','Leather',
      'Offense','Bail','Lights Out',
      'First Down','Banjo Hitter','Lumber',
      'Chip Shot','Barrel','Maddux',
      'Snap','Batter','Masher',
      'Quarterback','Belt','Meat',
      'QB','Big League','Bullseye',
      'LB','Major League','Dart',
      'Flea Flicker','Bigs','Midnight',
      'Fourth Down','Bronx Bomber','Moonshot',
      'FD','Bullpen','Olympus',
      'Fumble','Butcher Boy','Relay',
      'Fullback','Captain Hook','Ribbie',
      'FB','The Chair','Road Game',
      'Gridiron','Cheddar','Rookie',
      'Halfback','Chuck','Room Service',
      'HB','Clinic','Shoe String',
      'Huddle','Cookie','The Show',
      'Interference','Creature','Showboat',
      'Jack','Daisy Cutter','Shut Out',
      'Mo','Dead Red','Sinker',
      'Jumbo','Deuce','Skyscraper',
      'Juke','Earnie','Slap Hitter',
      'Monster Man','Evil Empire','Smoke',
      'NFL','Ump','Southpaw',
      'Pancake','Baller','Stats',
      'Red Shirt','Flamethrower','Stopper',
      'Red Zone','GM','Stretch',
      'Ref','Grand Slam','Tailgate',
      'Rover','Hammer','Tomahawk',
      'Sam','Hat Trick','Uncle Charlie',
      'Sideline','Goalie','Yardwork',
      'Side Zone','Offsides','Zinger',
      'Slobber-knocker','Home Plate','Ballgame',
      'Sneak','Homer','Matchpoint',
      'Split / Splits','Hook','Basket',
      'Handyman','The Talent','Chef',
      'Lumberjack','Officer','Astro',
      'Undertaker','The Philosopher','Buzz Aldrin',
      'Henchman','The Pro','Navigator',
      'Judge','Vet','Pilot',
      'Teach','The Specialist','Reverend',
      'Preach','Rep','Detective',
      'VP','HVAC','Inspector',
      'POTUS','Tinker','Undertaker',
      'Commander','Jail Bond','Marine',
      'Outlaw','Bazooka','Boomer',
      'Renegade','Chopper','Boomstick',
      'Champ','The Law','Booter',
      'Sentinel','Bullet','Box Kicker',
      'Colonel','The Enforcement','Captain Jack',
      'Recruit','Howitzer','Doughboy',
      'General','Patrol','FLAK',
      'Air Raid','Platoon','FUBAR',
      'Blitz','Saber','Hoover',
      'Blitzkrieg','Air Alert','Hun',
      'Atomic','Cannon','Iron',
      'Bootleg','Amphibian','Genghis',
      'Guard','HQ','Scuttlebutt',
      'Gunslinger','Armed Force','Trigger',
      'Gunner','Napoleon','Deck',
      'Pistol','Patton','Basecamp',
      'Rifle','Tank','Bomber',
      'AK47','Sub','D-Day',
      'Shield','WMD','Rocket',
      'West Coast','Sun Belt','German',
      'East Coast','Bible Belt','High Altitude',
      'Dirty Dirty','Pacific','Lowlands',
      'Rust Belt','Atlantic','Cornfed',
      'Piston','Wrangler','Rocker',
      'Xccelerator','Seatbelt','Clutch',
      'Motor','Volt','Shift',
      'Engine','Power Steering','Automatic',
      'Railroad','ATV','Gasoline',
      'Sparkplug','4-Wheel Drive','High-Octane',
      'Diesel','Hog','Gear Bait',
      'Cadillac','Fuse','Collision',
      'Hummer','Hydraulics','Nut',
      'The Keys','Fiddle','8-track',
      'Pipes','Breakdance','Frontflip',
      'Picasso','Half-Pipe','Hemingway',
      'Einstein','Kickback','Nobel Prize',
      'Banjo','Hard-Drive','Green Thumb',
      'Nintendo','2-bit','Lock Stock',
      'Sega','Code Master','Target',
    );

    protected static $femaleNicknames = array(
      '180','Uluru Walker','Hen Skittle',
      'Bad Beret','Clover Rabbit','TeederSmartie',
      'Mantis Queen','Evil Smith','BearDrift',
      '21st Street','White Dragon','NightWonka',
      'ManBreaker','Cinder Coffee','Pop Bee',
      'Racy Babe','Ella of Light','Taffy Duchess',
      'Abyss Tamer','Lady Katniss','Pixy Mox',
      'Heaven Sent','Scarlet Mary','9Lives',
      'DollFaceKillah','Little Granger','Double Eerie',
      'Acetic Princess','Princess Dove','Jelly Momentum',
      'Po1son','Bridge Whip','Toy Peep',
      'Rink Ruler','Poppin Loot','Street Jolly',
      'NightDream','Dorothy Solitaire','New York Sixlet',
      'Freeway','Juno Cream','Trash Pocky',
      'Bad Princess','Mrs. Voltage','Emerald Vine',
      'M8deUp','Baby Spell','Burst Nibbler',
      'Phoenix Sparrow','ZenaCake','Minty Devil',
      'Fire Queen','Mafia Rapunzel','Twix Esses',
      'Alley Fiend','Spit Turanga','NoiseCake',
      'Knock Out Star','Killer Curio','Trixie Doodle',
      'Twine X','Bat Magenta','Thumb Candy',
      'RZRWRE','Spoiler Betty','Apple Nola',
      'SprkR','Gold Dahlia','Troubled Pie',
      'Bad Beh8vior','Manly Reno','Devil Bread',
      'Chlorine','Jo Jo Spooky','Biscuit Meg',
      'Black Hole Necromancer','Gabriel Dandelion','Tweety Bun Bun',
      'Blood Taker','Ozzie Treat','Feral Cookie',
      'Ember Master','Spunky Sphinx','Pecan Oblivion',
      'Nice Gnome','Darkside Isis','Twinkle Cocoa',
      'VenusXX','Metal Aphrodite','Girl Brownie',
      'MeeP','Athena Star','Gamer Bean',
      'RightN0w2','Delicious Cupid','Undergrad Split',
      'Fire Sass','Microwave Chardonnay','Short Firecracker',
      'Engine Eye','Killer Merlot','Palomino Cake',
      'Intimidation Station','Digital Moonshine','Red Heroine',
      'Freeze Queen','Bourbon Mirage','Firefly Caramel',
      'Saturnalia','Steel Ginger','Gingersnap Woman',
      'Titanium Ladybug','Soda Delirium','S’more Vixen',
      'Cuff Queen','Miss Rum Punch','Flash Protein',
      'Boost Princess','Rummy Stickers','Fresh Peper',
      'Tin Fox','Demo Tequila','Tart Voodoo',
      'Spontan8ty','Lucky Brandy','Twisty Freesia',
      'Dark Burn','Barbera Shift','Juice Petite',
      'Alberta','Queen Ginger','Combo Saw',
      'Shadow Gal','Murder Cherry','Hitch Frenzy',
      'Referee','Berry Succubus','Pink C',
      'Noh Noh','Blue Despair','Snapple Whistler',
      'Shimmy Shammy','Black Mustard','Frosty Snazz',
      'Lumberyard','Sugar Apple','Aqua Diva',
      'Lil Rebel Ma','Divine Bramble','Swan Mustang',
      'Shy Warrior','Moon Peaches','Fuzzy Claws',
      'Red Delicious','Sun Lemon','Pitfall Whiskers',
      'High Heel Goddess','Doll Champagne','Trouble Mittens',
      'Show Boat','Martini Flower','Avenge Paws',
      'Cricket','Sweet Manhattan','Snout Pixie',
      'Pigeon Woman','Dez Bonbon','Wildcat Appaloosa',
      'Silver Agent','Plum Moon','Cougar Fuzz',
      'Alias Stick','Swedish Twizz','Pocket Muzzie',
      'Lady Peach','Sugar Domino','Wild Kitten',
      'Sky Trinity','Morbid Sugar','Slacker Cat',
      'Venom Charms','Tall Honey','Pepper Mouse',
      'Red Woman','Maple Destroyer','Friday Fox',
      'Sleek Zelda','Wanted Candy','Granola Dove',
      'Classy Luck','Plenty Orange','Purity Catnip',
      'Wonder Lady','Tootsie Killer','Bambi Wings',
      'HedgeH0g2','ButterQuest','Skittle Mine',
      'Bad Bunny','Willow Dragon','SmartieQuest',
      'Chip Queen','Reed Lady','DriftDetector',
      'Street Squirrel','White Snare','Night Magnet',
      'RoarSweetie','Poppy Coffee','Polar Bee',
      'Racy Lion','Light Lion','Subzero Taffy',
      'Chasm Face','Mint Ness','Pixie Soldier',
      'DuckDuck','Mum Mary','LifeRobber',
      'Killah Goose','Daffy Girl','Eerie Mizzen',
      'Acid Gosling','Fennel Dove','Jelly Camber',
      'Arsenic Coo','Cool Iris','Toy Dogwatch',
      'Roller Turtle','Marigold Loot','Vicious Street',
      'Alley Frog','Moon Solitaire','New York Winder',
      'Gullyway','Snow Cream','Trash Sling',
      'Romance Guppy','SunVolt','Green Scavenger',
      'Natural Gold','SpellTansy','Lava Nibbler',
      'Phoenix Tetra','TulipCake','Devil Blade',
      'Fire Fish','Sienna Princess','Twin Blaze',
      'Back Bett','Bug Fire','NoiseFire',
      'Koi Diva','Widow Curio','TrixiePhany',
      'Ember Rope','Pink Hopper','BlacKitten',
      'Congo Wire','Betty Cricket','Club Nola',
      'Impulsive Flower','Dahlia Bumble','Devil Chick',
      'Darling Peacock','Reno Monarch','Fire Feline',
      'Flame OUT','Spooky Yellowjacket','Nutmeg Riot',
      'RedMouth','VenusLion','NemesisX',
      'BloodEater','Lunar Treat','Feral Mayhem',
      'Terror Master','Spunky Comet','Fiend Oblivion',
      'Green Ghost','Darkside Orbit','Twinkle Cutlass',
      'Electric Saturn','Metal Star','Pearl Girl',
      'CoB@lt','LunaStar','Diamond Gamer',
      'Star Sword','Cupid Dust','Winter Bite',
      'Sass Burst','MicroStar','Fire Bite',
      'Mud Eye','Starshine','StormCake',
      'Cosmic Presence','Digital Equinox','Twister Hero',
      'Star Scratch','RetroMirage','Black Firefly',
      'Dakota Bliss','Steel Solstice','Blackfire',
      'Texas Butterfly','Delirious Supernova','Blizzard Vixen',
      'Geneva Cuffs','Miss Twilight','CirrusFlash',
      'Paris Boost','StarZen','PepperBurst',
      'London Fox','Demo Zero','Voodoo Cyclone',
      'Tokyo Dream','Lucky Aurora','Twisty Dew',
      'Dallas Burn','Bang Shift','Petite Flurry',
      'Nueva Nova','Ginger Chaos','Ship Whip',
      'Shady Prairie','Murder Matter','CloudFrenzy',
      'Milan Call Back','FireBerry','Pink Stream',
      'Roma Kabuki','Light Despair','SunnySnap',
      'Austin Shamrock','Miss Nova','Frosty Sunshine',
      'Athens Fire','Parallax Sugar','Aqua Monsoon',
      'Berlin Kamikaze','Divine Quasar','Breezy Mustang',
      'Bombay Shivers','Virgo Moon','Fuzzy Rainbow',
      'Kawaii Red','Sun Leo','Sand Whiskers',
      'California Goddess','X-Dew','Wiccan Thunder',
      'Cali Yacht','Moon Radar','Icy Avenger',
      'Lilac Lizard','True Sweetness','Snowflake Pixie',
      'Rosie Bird','Dez North','Jetta Talent',
      'Silver Rose','Moon Laser','Gold Bentley',
      'Daisy Stick','Pixie Taze','Pocket Mazda',
      'Black Fantastic','Domino Combat','Wild Tesla',
      'Sky Dahlia','FLAK Angel','Gothic Gucci',
      'Venom Petunia','SWAT Honey','Pepper Prada',
      'Lady Petal','Helmet Destroyer','Friday Ferrari',
      'Leaf Assassin','Kevlar Wanted','Dove Dolce',
      'Dance Bloom','Orange Teflon','Versace-Cat',
      'Lady Q','Killer Grenade','Bambi Benz',
      'Dakota','Dallas','Athena',
      'Bombay','Kawaii','Cali',
      'Lilac','Susie Q','Fennel',
      'Rosie','Buttercup','Iris',
      'Wild Rose','Willow','Marigold',
      'Daisy','Reed','Moonflower',
      'Black Lotus','Cattail','Snowdrop',
      'Dahlia','Dandelion','Sunflower',
      'Petunia','Snapdragon','Tansy',
      'Petal','Poppy','Tulip',
      'Leaf','Minty','Sienna',
      'Stem','Chrysanthemum','Sierra',
      'Bloomer','Daffodil','Mushroom',
      'Blue Lady','White Lady','Specter',
      'Red Lady','Casper','Shadow',
      'Banshee','Lele','Copycat',
      'Mad Dog','Ghost','Phantom',
      'Lady','Brown Eyes','Glitzy',
      'Ladygirl','Blue Eyes','Jewel',
      'Ladybird','Button','Be-Jewel',
      'Punkin','Doodle','Tator Tot',
      'Bubbles','Dumpling','French Fry',
      'Giggles','Noodle','Tinkerbell',
      'Dollface','Goobers','Twinkle Toes',
      'Vi-Vi','Snicky Snack','Muffy',
      'Gi-Gi','Pancake','Chuckles',
      'Zi-Zi','Waffle','Heart',
      'Pinkie','Cool-Whip','Valentine',
      'Rosebud','PB&J','Whizzy',
      'Lala','Peanut','Cheeto',
      'Belle','Tic Tac','Dorito',
      'Bitsy','Sparkles','Lolli',
      'Bitsy Boo','Glitter','Lollipop',
      'Vicious','Firestruck','Nemesis',
      'Winger','Epiphany','Mayhem',
      'Sling','Black Magic','Rubble',
      'Lava','Fight Club','Fiend',
      'Blade','Devil','Cutlass',
      'Scavenger','Fire Sign','Black Pearl',
      'Blaze','Riot','Black Diamond',
      'Empress','Princess','Missy',
      'Duchess','Queen','First Lady',
      'Countess','Miss','Mamsell',
    );


    /**
     * Return male nickname
     *
     * @example 'ELLerG!c'
     * @access public
     * @return string Nickname
     */
    public function maleNickname()
    {
        return static::randomElement(static::$maleNicknames);
    }

    /**
     * Return female nickname
     *
     * @example 'Lady Q'
     * @access public
     * @return string Nickname
     */
    public function femaleNickname()
    {
        return static::randomElement(static::$femaleNicknames);
    }

    /**
     * Return nickname, based on gender
     *
     * @param  string $gender   male|female
     * @return string           nickname
     */
    public function nickname($gender = null)
    {
        if ($gender === static::GENDER_MALE) {
            return static::maleNickname();
        } elseif ($gender === static::GENDER_FEMALE) {
            return static::femaleNickname();
        }

        return static::maleNickname();
    }
}
